### GET request to read all users
GET http://localhost:3000/api/v2/users

### POST request to create a new user
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
    "username": "happynewyear",
    "email": "happynewyear@example.com",
    "password": "12345678",
    "role": "admin"
}

### DELETE request to delete a user
DELETE http://localhost:3000/api/v2/users

### POST Login a user
POST http://localhost:3000/api/v2/users/auth/cookie/login
Content-Type: application/json

{
    "email": "happynewyear@example.com",
    "password": "12345678"
}


### POST Logout a user
POST http://localhost:3000/api/v2/users/auth/cookie/logout

### GET check user auth
GET http://localhost:3000/api/v2/users/auth/cookie/me
